// <auto-generated />
using System;
using GymTrackerProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymTrackerProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("GymTrackerProject.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GymTrackerProject.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Грудь",
                            Name = "Жим штанги лёжа"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Грудь",
                            Name = "Жим штанги в наклоне"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Грудь",
                            Name = "Жим гантелей лёжа"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Грудь",
                            Name = "Жим гантелей в наклоне"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Грудь",
                            Name = "Отжимания на брусьях"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Грудь",
                            Name = "Кроссовер на блоках"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Грудь",
                            Name = "Кроссовер на блоках"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Трицепс",
                            Name = "Отжимания"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Грудь",
                            Name = "Бабочка"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Грудь",
                            Name = "Кроссовер на блоках"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Грудь",
                            Name = "Разведение гантелей лёжа"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Грудь",
                            Name = "Разведение гантелей в наклоне"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Грудь",
                            Name = "Кроссовер в блоке"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Грудь",
                            Name = "Жим в хаммере"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Ноги",
                            Name = "Приседания со штангой"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Ноги",
                            Name = "Жим платформы"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Ноги",
                            Name = "Болгарские выпады"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Ноги",
                            Name = "Румынская тяга"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Ноги",
                            Name = "Гакк-приседания"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Ноги",
                            Name = "Разгибания ног в тренажёре"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Ноги",
                            Name = "Приседания с гантелями"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Ноги",
                            Name = "Сведение ног в тренажёре"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Ноги",
                            Name = "Разведение ног в тренажёре"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Ноги",
                            Name = "Сгибания ног лёжа"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Ноги",
                            Name = "Икры в тренажёре"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Ноги",
                            Name = "Икры со штангой"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Спина",
                            Name = "Гиперэкстензия"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Спина",
                            Name = "Тяга верхнего блока"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Спина",
                            Name = "Тяга нижнего блолка"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Спина",
                            Name = "Тяга штанги в наклоне"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Спина",
                            Name = "Подтягивания"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Спина",
                            Name = "Шраги с гантелями"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Спина",
                            Name = "Шраги со штангой"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Спина",
                            Name = "Тяга в хаммере"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Спина",
                            Name = "Становая тяга"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Бицепс",
                            Name = "Подъём штанги на бицепс"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Бицепс",
                            Name = "Подъём гантелей на бицепс"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Бицепс",
                            Name = "Молотки на бицепс"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Бицепс",
                            Name = "Подъём на бицепс в блоке"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Бицепс",
                            Name = "Подъём на бицепс в тренажёре"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Бицепс",
                            Name = "Подъём гантелей на бицепс сидя"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Спина",
                            Name = "Подъём гантелей на бицепс с сублимацией"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Трицепс",
                            Name = "Французский жим со штангой"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Трицепс",
                            Name = "Французский жим с гантелями"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Трицепс",
                            Name = "Жим гантели из-за головы"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Трицепс",
                            Name = "Разгибание рук с косичкой в блоке"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Трицепс",
                            Name = "Разгибание рук с прямой рукоятью в блоке"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Плечи",
                            Name = "Махи гантелями"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Плечи",
                            Name = "Тяга штанги к подбородку"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Плечи",
                            Name = "Армейский жим со штангой"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Плечи",
                            Name = "Армейский жим с гантелями"
                        },
                        new
                        {
                            Id = 52,
                            Category = "Плечи",
                            Name = "Обратная бабочка"
                        });
                });

            modelBuilder.Entity("GymTrackerProject.Entities.ProgressTracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("UpdatedProgress")
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Trackers", t =>
                        {
                            t.HasCheckConstraint("ValidReps", "Reps >= 0");

                            t.HasCheckConstraint("ValidWeight", "Weight >= 0");
                        });
                });

            modelBuilder.Entity("GymTrackerProject.Entities.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsersId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsersId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GymTrackerProject.Entities.ProgressTracker", b =>
                {
                    b.HasOne("GymTrackerProject.Entities.Exercise", "Exercise")
                        .WithMany("Progress")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTrackerProject.Entities.Workout", "Workout")
                        .WithMany("ProgressTrackers")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("GymTrackerProject.Entities.Workout", b =>
                {
                    b.HasOne("GymTrackerProject.Data.ApplicationUser", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GymTrackerProject.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GymTrackerProject.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymTrackerProject.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GymTrackerProject.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GymTrackerProject.Data.ApplicationUser", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("GymTrackerProject.Entities.Exercise", b =>
                {
                    b.Navigation("Progress");
                });

            modelBuilder.Entity("GymTrackerProject.Entities.Workout", b =>
                {
                    b.Navigation("ProgressTrackers");
                });
#pragma warning restore 612, 618
        }
    }
}
